apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment_initiation_api
  title: Payment Initiation
  description: Initiation of Payments.
  annotations:
   backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/backstage-poc/account-info-api/main/.spectral.yaml
  tags:
    - java
spec:
  type: openapi
  lifecycle: production
  system: Payments
  owner: payments-team
  definition:
    $text: ./payment-initiation-spec.json
